download:
  children:
    page:
      sort_by: title
      per_page: 10
blog:
  children:
    post:
      sort_by: published_at DESC
      per_page: 10
      children:
        comment:
          autherisation:
            delete: admin
            read: all
            create: all
            update: admin         
          sort_by: published_at
          field_map:
            name: cf_string_1
            email: cf_string_2
          body_length: 255
          body_strip_html: "true"
          randomise_permalink: "true"
          notify_admins: "true"
          flash_messages:
            create: You comment is now awaiting approval!
          per_page: 20
          default_state: pending
page:
  sort_by: title
  
gallery:
  children:
    gallery:
      sort_by: title
      per_page: 10
      children:
        picture:
          sort_by: title
          per_page: 10